version: "3.9"

services:
  api:
    build: .
    container_name: goapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
    networks:
      - goapi-net

  mongo:
    image: mongo:7.0
    container_name: mongo7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - goapi-net

volumes:
  mongo_data:

networks:
  goapi-net:
    driver: bridge
